name: Tests

on:
  pull_request:
    paths:
      - .github/workflows/tests.yml
      - src-tauri/**
  push:
    paths:
      - .github/workflows/tests.yml
      - src-tauri/**

defaults:
  run:
    working-directory: src-tauri

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: cargo fmt
        run: cargo fmt --all -- --check

  clippy-all-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Tauri dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: cargo clippy
        run: cargo clippy --all-features --all-targets -- -D warnings

  test-stable:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v7
      - name: Install Tauri dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: cargo test
        run: cargo test --all-features